name: Android AAB Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle (AAB)
      run: ./gradlew bundleDebug

    - name: Upload AAB File
      uses: actions/upload-artifact@v4
      with:
        name: protask-app-bundle
        path: app/build/outputs/bundle/debug/app-debug.aab
        
